spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: microspringboot-config-dev

---
spring:
     profiles: test
     application:
       name: microspringboot-config-test