spring:
  profiles:
    active: dev
---

spring:
  application:
    name: microspringcloud-config-3344
  cloud:
    config:
      server:
        git:
          uri: git@github.com:MarkerBrother/microspringcloud-config.git

  profiles:
    active: dev
---
spring:
  application:
    name: microspringcloud-config-3344
  cloud:
    config:
      server:
        git:
          uri: git@github.com:MarkerBrother/microspringcloud-config.git

  profiles:
    active: test