spring:
  profiles:
    active: dev
---

spring:
  application:
    name: microspringcloud-config-3344

  profiles:
    active: dev
---
spring:
  application:
    name: microspringcloud-config-3344

  profiles:
    active: test